name: Get GCMD Stats

on: [push]

jobs: 
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git pull
        python -m pip install --upgrade pip
        pip install pandas
        pip install matplotlib
        pip install xmltodict
        echo "done"
    - name: Run GCMD Count script
      run: |
        python3 gcmd.py
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git pull
        git add --all
        if [ -z "$(git status --porcelain)" ]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
